### ISSUE TITLE
Synchronized Video, Depth, and Audio Data

### ISSUE THREAD

**Issue by aiartsev** [MetalPetal/VideoIO#13]
Hi!

Am I missing something, or is there no way of adding a synchronized DataOutput with these three data types on the Camera object?

I've been using `public func enableSynchronizedVideoAndDepthDataOutput(on queue: DispatchQueue, delegate: AVCaptureDataOutputSynchronizerDelegate)`, but would really like to add audio capture to it instead of handling it in a separate delegate method.

Is there a reason this isn't done? I'm pretty new to audio/video capture and processing, so I might be missing something.

Thanks!!

**Comment by YuAo** [comment]
Can you provide more detail of your use case? I can't think of any real world scenario that requires the audio and video buffers to have the exact same timestamp.

**Comment by aiartsev** [comment]
It's not really a requirement, but it's something that could make the framework's client code more concise as there'd be no need to implement separate protocols or make two calls to the Camera object when one would be enough. Is there any benefits that come from the audio and video buffers not being synchronized?

**Comment by YuAo** [comment]
Video frames and audio packages come from different device, and in different time, and format. The problems caused by combining them in a single callback trump the API design benefit.
