### ISSUE TITLE
No output video buffers from AVPlayer using PlayerVideoOutput

### ISSUE THREAD

**Issue by ducle01490** [MetalPetal/VideoIO#16]
Hi,
I use PlayerVideoOutput to get video buffers from AVPlayer but there is no output. I found that handleUpdate() function does not called because self is nil. (File: [PlayerVideoOutput.swift, line 162](https://github.com/MetalPetal/VideoIO/blob/ef9face95989a89a8425561b30d3e45d4b47c354/Sources/VideoIO/PlayerVideoOutput.swift#L162)).

By the way, is it possible if using VideoIO and MetalPetal to blend a video with another video?
Thank you so much for awesome lib!

**Comment by YuAo** [comment]
1. You need to retain the `PlayerVideoOutput` to prevent it from deinit.
2. Yes, you can blend two videos. The suggestion is to create a `AVComposition` with tracks from two videos,  then use `MTIVideoComposition` to apply a filter.

**Comment by ducle01490** [comment]
Thank you for your immediate response.
I have tried it and it works very well!
