### ISSUE TITLE
Wrong audioTracks being added in audioOutput inside AssetExportSession

### ISSUE THREAD

**Issue by casper6479** [MetalPetal/VideoIO#17]
Currently, audioTracks from asset before copy are different with asset after copy, so AVAssetReader will return false in this case when reader.canAdd(audioOutput), so export will fail with error cannotAddAudioOutput

**Comment by YuAo** [comment]
Can you provide more detail of this issue? Maybe some examples to reproduce it.

I think the copying is only effective when the asset is an `AVMutableComposition` (copying makes an `AVComposition`), both order and id of the tracks do not change in this case. In other cases, the asset is an immutable object (`AVURLAsset`, `AVComposition`) and the `copy` method should just return the object itself.
