### ISSUE TITLE
Unable to set Frame rate to 60fps for 'vide'/'x420' 3840x2160

### ISSUE THREAD

**Issue by BenK1934** [MetalPetal/VideoIO#19]
Hi   
I'm Using VideoIO in conjunction with your terrific Metal Petal and I have a problem.
When I use Camera.Configurator() to setup the camera  and then do a search for available formats using
print("Available device formats are \(self.camera.videoDevice!.formats)")
it does not return the 'vide'/'x420' 3840x2160 { 1- 60 fps} option in the list of available formats.

I think this is due to the use of the AVCaptureDevice.DiscoverySession in VideoIO Camera.swift.

Is there a way to still use VideoIO to set up the camera device and get access to the other formats?

Thanks and sorry if this is an amateur beginner question.

**Comment by YuAo** [comment]
@BenK1934 I think you can use `Camera.switchToVideoCaptureDevice(with position:preferredDeviceTypes:)` to select video devices using your preferred device types, before starting the camera.  The `position` and `preferredDeviceTypes` is used to create the discovery session.

**Comment by BenK1934** [comment]
Thankyou YuAo, yes I'm getting the device correctly however using an available formats search after the discovery session does not return all the available formats. It does not include the 3840x2160 formats that go to 60fps.
I've noticed that if I use AVCaptureDevice.default(for: .video) instead of the discovery session in VideoIO Camera.swift. it does return all the available formats. ( However currently it creates other problems)

**Comment by YuAo** [comment]
Can you take a look at the default device's type, and use that type for the discovery session?

**Comment by YuAo** [comment]
I run the following code on an iPhone 12 Pro.
```
configurator.videoDeviceConfigurator = { camera, device in
            for format in device.formats {
                print(format)
            }
        }
let camera = .....
try! camera.switchToVideoCaptureDevice(with: .back, preferredDeviceTypes: [.builtInWideAngleCamera])
```
It gives me the 60fps 4k HDR format.
```
<AVCaptureDeviceFormat: 0x2824fe2c0 'vide'/'x420' 3840x2160, { 1- 60 fps}, fov:68.161, supports vis, max zoom:125.25 (upscales @1.00), AF System:2, ISO:34.0-3264.0, SS:0.000014-1.000000, supports wide color>
```
