### ISSUE TITLE
Focus hunting  on .builtInWideAngleCamera on iPhone 12 pro

### ISSUE THREAD

**Issue by BenK1934** [MetalPetal/VideoIO#22]
Hi Thanks again for the very useful VideoIO, I'm using this in conjunction with Metal Petal.
I'm having a problem with focus hunting currently only on the .builtInWideAngleCamera on an iPhone 12 pro on iOS 14.6.

I'm setting up the wide angle camera using

`try self.camera.switchToVideoCaptureDevice(with: .back, preferredDeviceTypes: [.builtInWideAngleCamera])`

and setting continuous auto focus with

`        queue.async{
        let device = self.camera.videoDevice!
        do {
            try device.lockForConfiguration()
            if device.isFocusPointOfInterestSupported && device.isFocusModeSupported(.continuousAutoFocus) {
                device.focusPointOfInterest = focusPoint
                device.focusMode = .continuousAutoFocus
            }
            if device.isSmoothAutoFocusSupported {
                device.isSmoothAutoFocusEnabled = true
            }
            device.unlockForConfiguration()
        } catch {
            print(error)
        }
        }`
using the same setup on the telephoto lens works perfectly but on the WideAngle camera I get the focus hunting. Any clues what might be causing this?

**Comment by YuAo** [comment]
Can you check the `autoFocusSystem` of the device's active format?
```
device.activeFormat.autoFocusSystem
```

You may want to choose a format with the `phaseDetection` focus system.

**Comment by BenK1934** [comment]
YuAo you are terrific!  I'm again extremely impressed with the depth of your knowledge
that was exactly it I filtered the formats for phaseDetection
`if format.autoFocusSystem.rawValue == 2`
and that solved it. Thanks.
