### ISSUE TITLE
How to switch microphone inputs to stereo?

### ISSUE THREAD

**Issue by BenK1934** [MetalPetal/VideoIO#23]
Hi 
Sorry for another beginner question but I'm try to set the microphone input to stereo, 
I can see that self.camera.audioDevice returns the default microphone
[iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]
and that self.camera.audioCaptureConnection?.audioChannels.count is 1

At what point do I access the numberOfChannels and  channelLayout? in AudioSettings? to set microphone to stereo?

**Comment by YuAo** [comment]
You'll need to setup a stereo audio session. https://developer.apple.com/videos/play/wwdc2020/10226/

```
try audioSession.setPreferredInput(builtInMic)
try preferredDataSource.setPreferredPolarPattern(.stereo)
try builtInMic.setPreferredDataSource(preferredDataSource)
try audioSession.setPreferredInputOrientation(preferredInputOrientation)
```

I'm not sure whether the AVCaptureSession is able to record stereo audio, I usually use the `AudioQueueCaptureSession`.  

You are welcome to post your research here.

**Comment by BenK1934** [comment]
Thank you for the tips YuAo, I'm working on it using info found at https://developer.apple.com/documentation/avfaudio/avaudiosession/capturing_stereo_audio_from_built-in_microphones
It's at the limits of my skills but I'll let you know how I go.
