### ISSUE TITLE
Cannot Encode Media on AssetExportSession

### ISSUE THREAD

**Issue by ostrovdi** [MetalPetal/VideoIO#25]
Sometimes I'm facing with issue when for input .mp4/.mov file returns error "Cannot Encode Media".

Attaching video examples which cases such kind of error.
Also here it's my configs:
`
func getConfiguration(for asset: AVAsset) -> AssetExportSession.Configuration? {
    guard let videoTrack = asset.tracks(withMediaType: .video).first else {
        return nil
    }

    let estimatedSize = __CGSizeApplyAffineTransform(videoTrack.naturalSize, videoTrack.preferredTransform)
    let size: CGSize
    if abs(estimatedSize.width) > abs(videoTrack.naturalSize.height) {
        size = .init(width: 1280, height: 720)
    } else {
        size = .init(width: 720, height: 1280)
    }

    if (asset as? AVURLAsset)?.url.pathExtension.lowercased() == GlobalConstants.Video.mediaFormatType,
       videoTrack.nominalFrameRate <= Float(GlobalConstants.Video.fps + 1),
       videoTrack.naturalSize == size,
       videoTrack.estimatedDataRate <= Float(GlobalConstants.Video.averageBitRate) {
        return nil
    }

    var audioSampleRate: Double = 44100
    var audioBitrate = 128 * 1000
    var numberOfChannels: Int = 2

    if let audioTrack = asset.tracks(withMediaType: .audio).first,
       let formatDescription = audioTrack.formatDescriptions.first,
       let basic = CMAudioFormatDescriptionGetStreamBasicDescription(formatDescription as! CMAudioFormatDescription) {
        audioSampleRate = basic.pointee.mSampleRate
        audioBitrate = Int(audioTrack.estimatedDataRate)
        numberOfChannels = Int(basic.pointee.mChannelsPerFrame)
    }

    return .init(fileType: .mp4,
                 videoSettings: .h264(videoSize: size, averageBitRate: min(GlobalConstants.Video.averageBitRate, Int(videoTrack.estimatedDataRate))),
                 audioSettings: .aac(channels: numberOfChannels, sampleRate: audioSampleRate, bitRate: audioBitrate))
}
`

Testing device: iPhone Xs, iOS 14.5.1
Pod version: 2.2.0

https://user-images.githubusercontent.com/26931446/130083374-8a26c8a3-7837-4ec0-ad02-49ca522aff19.mp4

https://user-images.githubusercontent.com/26931446/130083345-f5867b75-42dd-459e-ba73-1175fbeb9fd0.mov

**Comment by YuAo** [comment]
Try using a fixed audio bitrate, for example 128000, instead of `audioTrack.estimatedDataRate`.

You can find out whether the audio bitrate is applicable by creating a `AVAudioConverter` and query the `applicableEncodeBitRates`.

```
var targetFormat = AudioStreamBasicDescription()
targetFormat.mFormatID = kAudioFormatMPEG4AAC
targetFormat.mSampleRate = 44100
targetFormat.mChannelsPerFrame = 2
targetFormat.mFramesPerPacket = 1024
let toFormat = AVAudioFormat(streamDescription: &targetFormat)

let fromFormat = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 44100, channels: 2, interleaved: true)

let converter = AVAudioConverter(from: fromFormat!, to: toFormat!)
print(converter!.applicableEncodeBitRates)
```

**Comment by ostrovdi** [comment]
Thank you @YuAo, that helps!

Can you please add some info how to change fps for video as for now I can see only size and bitrate configs.
Thanks in advance.

**Comment by YuAo** [comment]
For changing frame rate you may want to use `AVVideoComposition.frameDuration`
