### ISSUE TITLE
Never ready for audio

### ISSUE THREAD

**Issue by dsmurfin** [MetalPetal/VideoIO#27]
I am trying to figure out what is going on with appending audio samples on macOS.

I have a few scenarios which seem to get different results.

If I add an internal Mac microphone alongside an external webcam video, then audio input is added successfully, and Line 440 of `MultitrackMovieRecorder.swift` is called to append the sample buffer.

If I add the microphone integrated into the webcam instead, then I fail at line 412 of `MultitrackMovieRecorder.swift`, and buffers are progressively added to `pendingAudioSampleBuffers`. Somehow though, audio is still recorded in this scenario which is confusing.

Lastly, if I add a non AVFoundation video and audio buffer then I get the same results as the webcam audio and video where both are recorded, but buffers are continually added to `pendingAudioSampleBuffers`.

Any thoughts much appreciated.

**Comment by YuAo** [comment]
`MultitrackMovieRecorder` has an internal mechanism that ensures the first and last frame of your recording are video frames. If it receives an audio buffer with a time stamp larger than the previous video buffer, it caches that audio buffer till a later video buffer is received.

**Comment by dsmurfin** [comment]
Yes, I noticed that. What I seen to see though is that the buffers are just continually added, and never actually get processed. I am guessing this is because the presentation times are different and so the audio is never processed if it has a much later CMTime value.

**Comment by YuAo** [comment]
Yes, the audio buffers may not be processed if no later video buffers are appended.

I do think the current strategy has a lot of room for improvements.

For example: 
- Drop audio buffers if the count/size of the pending audio buffers exceeds some limit. 
- Check the pending audio buffers after encoding a video buffer.

**Comment by dsmurfin** [comment]
Thanks. Yes, would be good to tighten it up a bit at some point to cover this edge case.

Thanks again.
