### ISSUE TITLE
Frames no longer being appended

### ISSUE THREAD

**Issue by dsmurfin** [MetalPetal/VideoIO#28]
Hi @YuAo 

Thanks as ever for your thoughts. This is a little more of a question than an issue, although it's possible there does need to be some code changes.

I'm having some issues where a video will be recorded of the correct length, but after a certain amount of time frames stop changing. No errors seem to be thrown (or at least I'm not capturing them).

I'm wondering if this could be an issue with wrapping source time related to the following line in MultitrackMovieRecorder, as opposed to using CMTime.zero?

`self.assetWriter.startSession(atSourceTime: presentationTime)`

This is the text from the docs for this method:

```
In the case of the QuickTime movie file format, the first session begins at movie time 0, so a sample
you append with timestamp T plays at movie time (T-startTime). The writer adds samples with
timestamps earlier than the start time to the output file, but they don’t display during playback.
```

Thanks as ever!

**Comment by YuAo** [comment]
I think the current implementation is perfectly fine according to the documentation you referred.

There are two kind of time `movie time` and `sample time (source time)`.

> a sample you append with timestamp T plays at movie time (T-startTime)

If the session begins at sample time T, then simple with time T begins at "movie time" `(T - startTime) => (T - T) => 0`

---

Anyway, can you provide more detail about the issue you encountered? 

Is there an error reported when you call `stopRecording(completion:)`? 
Is there something like "Video inputs: not ready for media data" in the console?
What about the recording duration reported in the `durationChangedHandler`?

**Comment by YuAo** [comment]
It seems to be the case that the writer failed to append more frames duration recording:

https://github.com/MetalPetal/VideoIO/blob/50310e6fa2793f36dc6d16735d26dee07cf3c380/Sources/VideoIO/MultitrackMovieRecorder.swift#L215-L228

This could be caused by:

- Appending a frame that has earlier/equal timestamp than a previously appended frame.
- There's no enough disk space.
- ...

**Comment by dsmurfin** [comment]
> There's no enough disk space.

I think we may be running into this. Of course this just returns here rather than throwing, so unless we check the error state we don't know what has happened until we attempt to finalize the recording.

**Comment by YuAo** [comment]
I'll take a closer look at this later this weekend.

**Comment by dsmurfin** [comment]
Amazing. Thank you.
