### ISSUE TITLE
Create CocoaPod

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/VideoIO#3]
I started using MetalPetal for Video, but has found that VideoComposition is an important part of video processing.

So what do you think about making this library as a part of CocoaPods. Or making subspec for  MetalPetal?

**Comment by YuAo** [comment]
Sounds good.

Could you explain why you don't use Swift PM?

**Comment by larryonoff** [comment]
@YuAo I prefer using only one dependencies manager. All my dependencies are under CocoaPods at the moment.

**Comment by YuAo** [comment]
You should be able to use CocoaPods now. Ref: https://github.com/MetalPetal/VideoIO/runs/687861616?check_suite_focus=true

**Comment by larryonoff** [comment]
@YuAo thank you! it was fast!
